name: "Open Github Issue"
author: Carey Boldenow
description: "Opens a github issue"
inputs:
  token:
    description: "Github Token"
    required: true
  title:
    description: "Issue Title"
    required: true
  body:
    description: "Issue Body"
    required: true
  assignees:
    description: "Issue Assignees"
    required: false
outputs:
  issue: # id of output
    description: "The issue object as a json string"
runs:
  using: "node16"
  main: "dist/index.js"